DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM ('Main', 'Snack', 'Lunch', 'Breakfast');

CREATE TABLE IF NOT EXISTS shopping_list (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_name TEXT NOT NULL,
    item_price TEXT NOT NULL,
    item_date_added TIMESTAMP DEFAULT now() NOT NULL,
    item_checked BOOLEAN DEFAULT false NOT NULL,
    item_category grocery
);